models:
    - name: ssd512
      launchers:
        - framework: dlsdk
          device: CPU
          adapter: ssd
          num_requests: 8

      datasets:
        - name: VOC2007
          data_source: data/voc/VOCdevkit/VOC2007/JPEGImages
          annotation_conversion:
            converter: voc_detection
            annotations_dir: data/voc/VOCdevkit/VOC2007/Annotations
            images_dir: data/voc/VOCdevkit/VOC2007/JPEGImages
            imageset_file: data/voc/VOCdevkit/VOC2007/ImageSets/Main/test.txt
          annotation: data/voc/voc07.pickle
          dataset_meta: data/voc/voc07.json
          preprocessing:
            - type: resize
              size: 512
          postprocessing:
            - type: resize_prediction_boxes
          metrics:
            - type: map
              integral: 11point
              ignore_difficult: True
              presenter: print_scalar