models:
    - name: ssd512
      launchers:
        - framework: dlsdk
          adapter: ssd
          num_requests: 8
          device: CPU

      datasets:
        - name: VOC2007
          data_source: voc/VOCdevkit/VOC2007/JPEGImages
          annotation_conversion:
            converter: voc_detection
            annotations_dir: voc/VOCdevkit/VOC2007/Annotations
            images_dir: voc/VOCdevkit/VOC2007/JPEGImages
            imageset_file: voc/VOCdevkit/VOC2007/ImageSets/Main/test.txt
          annotation: voc07.pickle
          dataset_meta: voc07.json
          preprocessing:
            - type: resize
              size: 409
          postprocessing:
            - type: resize_prediction_boxes
          metrics:
            - type: map
              integral: 11point
              ignore_difficult: True
              presenter: print_scalar