models:
  - name: fastseg-large
    launchers:
      - framework: dlsdk
        adapter:
          type: segmentation
          make_argmax: True
        device: CPU
        num_requests: 8
    datasets:
      - name: cityscapes
        annotation_conversion:
          converter: cityscapes
          dataset_root_dir: Cityscapes

        data_source: Cityscapes
        annotation: cityscapes.pickle
        dataset_meta: cityscapes.json
        metrics:
          - type: mean_iou
            use_argmax: false
            presenter: print_scalar
