models:
  - name: efficientnet-b7-pytorch
    launchers:
      - framework: dlsdk
        adapter: classification
        device: CPU
        num_requests: 8
    datasets:
      - name: imagenet_1000
        reader: pillow_imread
        annotation_conversion:
          converter: imagenet
          annotation_file: imagenet/ILSVRC2015_val.txt
        annotation: imagenet1000.pickle
        data_source: imagenet
        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1
          - name: accuracy@top5
            type: accuracy
            top_k: 5

        preprocessing:
          - type: rgb_to_bgr

          - type: resize
            size: 632
            aspect_ratio_scale: greater
            use_pillow: True
            interpolation: BICUBIC
            # Crop ratio 0.949
          - type: crop
            use_pillow: True
            size: 600