models:
  - name: faster_rcnn_inception_resnet_v2_atrous_coco
    launchers:
      - framework: dlsdk
        adapter: ssd
        device: CPU
        num_requests: 24
        inputs:
          - name: image_info
            type: CONST_INPUT
            value: [ [ 600, 1024, 1 ] ]

    datasets:
      - name: ms_coco_detection_91_classes
        annotation_conversion:
          converter: mscoco_detection
          annotation_file: coco/val2017/instances_val2017.json
          has_background: True
          sort_annotations: True
          use_full_label_map: True
        annotation: coco/val2017/mscoco_det_91.pickle
        dataset_meta: coco/val2017/mscoco_det_91.json
        data_source: coco/val2017/
        preprocessing:
          - type: resize
            aspect_ratio_scale: fit_to_window
            dst_height: 600
            dst_width: 1024
          - type: padding
            dst_height: 600
            dst_width: 1024
            pad_type: right_bottom
        postprocessing:
          - type: faster_rcnn_postprocessing_resize
            dst_height: 600
            dst_width: 1024
        metrics:
          - type: coco_precision
            max_detections: 100
          - type: map
            integral: 11point
            presenter: print_scalar
            ignore_difficult: true
  
